# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  development:
    id: optimism-main-fork
    cmd: ganache-cli
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
      port: 8545
      gas_limit: 20000000
      accounts: 10
      evm_version: istanbul
      mnemonic: brownie
      fork: optimism-main


# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - yearn/yearn-vaults@0.4.3-1sol8
  - OpenZeppelin/openzeppelin-contracts@4.4.1

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.12
    remappings:
      - "@yearn/yearn-vaults=yearn/yearn-vaults@0.4.3-1sol8"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"

reports:
  exclude_contracts:
    - SafeMath
